# Copyright Tecnalia Research & Innovation (https://www.tecnalia.com)
# Copyright Tecnalia Blockchain LAB
#
# SPDX-License-Identifier: Apache-2.0

FROM arm64v8/node:8.15.0

# default values pf environment variables
# that are used inside container

ENV DEFAULT_WORKDIR /opt
ENV EXPLORER_APP_PATH $DEFAULT_WORKDIR/explorer

# database configuration
ENV DATABASE_HOST 127.0.0.1
ENV DATABASE_PORT 5432
ENV DATABASE_NAME fabricexplorer
ENV DATABASE_USERNAME hppoc
ENV DATABASE_PASSWD password

ENV STARTUP_SCRIPT /opt

# set default working dir inside container
WORKDIR $DEFAULT_WORKDIR

# copy external data to container
COPY . $EXPLORER_APP_PATH

# install NPM dependencies
RUN cd $EXPLORER_APP_PATH && npm install

# build explorer app
RUN cd $EXPLORER_APP_PATH && cd client && npm install && npm install browserslist caniuse-lite && npm run build

# expose default ports
EXPOSE 8080

# run blockchain explorer main app
CMD node $EXPLORER_APP_PATH/main.js && tail -f /dev/null
